# Generated by Django 5.2.7 on 2025-11-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0003_userprofile_created_at_userprofile_telegram_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tariffs',
            new_name='Tariff',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
