# Generated by Django 5.2.7 on 2025-11-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0004_rename_tariffs_tariff_alter_userprofile_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcasts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('media', models.FileField(blank=True, null=True, upload_to='broadcasts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('send_at', models.DateTimeField(blank=True, null=True)),
                ('sent', models.BooleanField(default=False)),
            ],
        ),
    ]
