# Generated by Django 5.2.7 on 2025-11-10 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0005_broadcasts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Broadcasts',
            new_name='Broadcast',
        ),
    ]
