# Generated by Django 5.2.7 on 2025-11-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0006_rename_broadcasts_broadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bonus_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
